### Part 1

Write a script to generate an
p
-ER random graph

From scratch

In [ ]:
#from scipy.special import comb
#import numpy as np
#import igraph
import random
from triarray import TriMatrix

def pEr_mod1(n = 5, m = 3):
    # compute the number of edges n(n-1)/2
    D = comb(n, m, exact=True)
    # choose at random m indexes where to put edges
    i = np.random.choice(D, m, replace=False)
    # build a D dimensional vector containing the edges
    v = np.array([1 if k in i else 0 for k in range(D)])
    print(v)
    R = []
    for i in range(0,n-1):
        for j in range(i,n): 
            R[i][j] = v[i+j]
    print(i, v, R)
    

    
#def pEr_mod2(n = 10, p = 0.50):
comb(5,3)

Using libraries

In [12]:
import networkx as nx
import matplotlib.pyplot as plt
import numpy.linalg as alg
import numpy as np

n = 6
m = 3
p = 0.3
r = 5

# create a G_n,m random graph
Gnm = nx.gnm_random_graph(n = n, m = m)
# the adjacency matrix
A_Gnm = nx.to_numpy_matrix(Gnm)
# create a G_n,p random graph
Gnp = nx.gnp_random_graph(n=n, p=p)
# the adjacency matrix
A_Gnp = nx.to_numpy_matrix(Gnp)
# create a r-regular random graph
rrG = nx.random_regular_graph(d=r, n=n)
# the adjacency matrix
A_rrG = nx.to_numpy_matrix(rrG)

'''nx.draw(rrG)
plt.show()
nx.info(rrG)'''



'nx.draw(rrG)\nplt.show()\nnx.info(rrG)'

Write a script to generate an
r
-regular random graph.


Write a script to check the connectivity of a given graph.
- algebraic method 1 (irreducibility);
- algebraic method 2 (eigenvalue of the Laplacian matrix);
- breadth-first search algorithm.


In [8]:
# Irreducibility

def irredicibility(matrix):
    n = matrix.shape[0]
    S = np.zeros((n,n))
    for n in range(n):
           S = S + alg.matrix_power(M=matrix, n=n)
    if S.any() > 0: 
        print('The graph is irreducible,\n-> The graph is connehence connected')
    


irredicibility(A_rrG)

The graph is irreducible,
-> The graph is connehence connected


In [15]:

# Eigenvalue of the Laplacian Matrix

def Laplacian(graph):
    # adjacency matrix
    A = nx.to_numpy_matrix(graph)
    # degree matrix
    #print([degree[1] for degree in nx.degree(G = graph)])
    D = np.diag([degree[1] for degree in nx.degree(G = graph)])
    # laplacian matrix
    L = D - A
    print(L)
    return(L)

L = Laplacian(rrG)
np.sort(alg.eig(L)[0])

[[ 5. -1. -1. -1. -1. -1.]
 [-1.  5. -1. -1. -1. -1.]
 [-1. -1.  5. -1. -1. -1.]
 [-1. -1. -1.  5. -1. -1.]
 [-1. -1. -1. -1.  5. -1.]
 [-1. -1. -1. -1. -1.  5.]]


array([ -5.55111512e-16,   6.00000000e+00,   6.00000000e+00,
         6.00000000e+00,   6.00000000e+00,   6.00000000e+00])

In [111]:
# Breath first search
# finds all paths for a given node
rrG.nodes[]

NodeView((0, 1, 2, 3, 4, 5))

Compare the complexity as a function of
n
of the methods
above.

Let
p
c
(
G
) denote the probability that a graph
G
is connected.

Produce two graphs:
p
c
(
G
) vs.
p
for Erd ̋os-R ́enyi graphs
G
(
n
,
p
) with
n
= 100.
p
c
(
G
) vs.
n
for
r
-regular random graphs with
r
= 2
,
4
,
8
,
16
and
n
ranging up to 100.

### Part 2 

Throughput performance
Write a script that:  
- (i) generates a random graph describing
the topology of the ToR switch network; 
- (ii) checks its
connectivity; 
- (iii) finds shortest path routes; (iv) estimates
h
.

Use both the
r
-regular random graph model and the
p
-Erd ̋os-R ́enyi random graph model.  In either case let
n
be the
number of nodes (you can assume 9
≤
n
≤
100,
r
= 8 and
p
= 8
/
(
n
−
1))

Plot the application-oblivious throughput bound
TH
, as
defined above, versus
n
for the two graph models.

Reliability performance

Assume a link can break down (fail) with probability
q
.

Plot
TH
as a function of
q
for 0
<
q
≤
0
.
25, for the two
network models in point 1) above with
n
= 100.